"""add_otp_fields

Revision ID: 876ce331ae0b
Revises: 3021c9361920
Create Date: 2026-02-25 05:16:59.174484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "876ce331ae0b"
down_revision: Union[str, Sequence[str], None] = "3021c9361920"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_verified", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("users", sa.Column("otp_code", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("otp_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_expires_at")
    op.drop_column("users", "otp_code")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
